image: alpine:latest

stages:
  - development

cache:
  paths:
    - node_modules/

development:
  stage: development
  only:
    - develop
  before_script:
    - apk --no-cache add openssh rsync
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

#   script:
    # - ssh-add <(echo "$SSH_PRIV_KEY")
    # - rsync -azv --exclude .git --exclude node_modules . iotech@$DEPLOY_HOST_DEV:$WORKDIR
    # - ssh -p22 iotech@$DEPLOY_HOST_DEV "cd $WORKDIR"
