name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -azv
        path: ./
        remote_path: ${{ secrets.WORKDIR }}
        remote_host: ${{ secrets.DEPLOY_HOST_DEV }}
        remote_user: iotech
        remote_key: ${{ secrets.SSH_KEY }}
